### ISSUE TITLE
problem upgrading package

### ISSUE THREAD

**Issue by bburdette** [ellie-app/ellie#102]
I upgraded elm-ui on an ellie to 1.1.5, but it still shows the bug it had from elm-ui 1.1.0.  

https://ellie-app.com/6ny7kDgfTY3a1

Here's one I created from scratch that doesn't have the elm-ui lib problem.  The first text box should be 3 lines high, and here it works.

https://ellie-app.com/6ny8WkYDyfHa1

Both examples have the same Main.elm and the same package versions.

**Comment by bburdette** [comment]
Uh, ok I just tried it over on Chrome, and it seems I got bitten by the dealio where it won't recompile unless there's a change in my code - library version changes don't merit a recompile.  Don't know if that's really in the bailywick of ellie, but I think it would be helpful to force a recompile on version changes.

**Comment by tbash** [comment]
Thanks for reporting back! Closing for now as I don't think I'll be making a change here.
