### ISSUE TITLE
Keyboard shortcut for Format Elm Code does nothing

### ISSUE THREAD

**Issue by lydell** [ellie-app/ellie#106]
If you hover the Format Elm Code button in the top-right of the editor, the tooltip says: "Format Elm Code (⇧⌥F)".

But pressing ⇧⌥F does not appear to do anything. I’ve tried both in Firefox and Chrome. I also switched from my usual Swedish keyboard layout to the standard en-US one, but it made no difference.

Also, the tooltip says to press ⇧⌥F on Windows and Linux as well, even though those systems have no ⌥ key.

**Comment by tbash** [comment]
Removing  (⇧⌥F) text for now. Will revisit UI that summarizes all keyboard shortcuts and considers different keyboard layouts.
