### ISSUE TITLE
Bad error message when compilation fails due to bad Internet connection

### ISSUE THREAD

**Issue by lydell** [ellie-app/ellie#108]
I used Ellie on the train the other day. Just after I had clicked Compile, I lost Internet connection for a bit. Result:

> **Compiling failed**
> Ellie was unable to compile your code. Compiling should always work, so this has been automatically reported to the maintainers.

![Screenshot from 2019-09-07 14-48-43](https://user-images.githubusercontent.com/2142817/64475124-af618880-d17e-11e9-963e-27ddd27a8193.png)

This can easily be reproduced by turning off WiFi/Internet before clicking Compile.

Also, the Compile button was then disabled forever. So was the Save button. So I had to copy the Elm code and the HTML code to some temporary files, reload the page and paste the code back.

As a bonus, if you try to click the Reload button while Compile is taking time (or after Compile has failed) you get this error:

> **Exception Thrown in Output**
> ReferenceError: Elm is not defined

![Screenshot from 2019-09-07 14-51-42](https://user-images.githubusercontent.com/2142817/64475158-2eef5780-d17f-11e9-8d14-0d8886742504.png)

Which is fine I guess. Or something like “Last compilation failed. Please compiling again!”. Or maybe autorun Compile.

**Comment by tbash** [comment]
Incoming fix for this, will be in master shortly! Turns out going back online after going offline broke somewhere along the way 😅  Thanks!
