### ISSUE TITLE
embedded text/elm support

### ISSUE THREAD

**Issue by fkowal** [ellie-app/ellie#109]
First of all I love how ellie allows to easily get started / hacking on Elm!!

Question:
Is it possible to achieve the following using ellie ?
```html
<script src="???ellie???"></script>
<script type="text/elm"> <!--
// here goes the elm sourcecode
</script>
<script>Elm.Main.init({ node: document.querySelector('main') })</script>
```

**Comment by tbash** [comment]
Glad you're loving it!

There is now way to currently achieve what you mentioned nor is it something that is on the roadmap. Currently Elm code is compiled on the server and the JS binary is received but is not persisted anywhere (well it is but only temporarily) making something like this potentially expensive.

Certainly not quite as easy as this happening automatically but you could compile your source code and host it yourself using S3.

Keep hacking! ❤️
