### ISSUE TITLE
Missing / in link to the package causes 404 down the line

### ISSUE THREAD

**Issue by jfmengels** [ellie-app/ellie#110]
This is related to a bug I uncovered and reported in the Elm packages repo: https://github.com/elm/package.elm-lang.org/issues/313

# SSCCE 

- Open a new Ellie, and go to the packages tab
- Install the jfmengels/review-debug package
- Click on that package's associated "VIEW DOCS" button
- On the package's documentation, click on the `NoDebug` link in the README (not the table of contents)
- Notice a 404 not found error

# Explanation

The problem is that the "VIEW DOCS" button links to https://package.elm-lang.org/packages/jfmengels/review-debug/1.0.0, which is missing a trailing slash. In the README, the `NoDebug` link links to a relative URL `./NoDebug`. Without the trailing slash in the URL, this links to https://package.elm-lang.org/packages/jfmengels/review-debug/NoDebug, but we actually want to link to be https://package.elm-lang.org/packages/jfmengels/review-debug/1.0.0/NoDebug.

# Probable solution

Add a trailing slash to the link to the package.

Let me know if you would like help with fixing this.

### By the way

Thanks a lot to all the contributors for this awesome project!

**Comment by tbash** [comment]
Thanks for reporting! Looks like this was resolved at the source, nothing to do here now. I could not recreate but if this is still an issue please feel free to reopen this. ✌️

**Comment by jfmengels** [comment]
Thanks for looking at it :)

I have recently published a new version of `review-debug` where the docs are now different and do have the trailing slash.

The issue still happens for packages like `jfmengels/lint-debug`.
I can't re-open the issue by the way, so I'll let you do that if you can reproduce it.
