### ISSUE TITLE
Can't get back to program from debugger

### ISSUE THREAD

**Issue by malaire** [ellie-app/ellie#111]
When running the default program in Ellie, and then clicking the debugger symbol in bottom-right corner, there is no way to close the debugger and see normal program output again, without restarting the program.

This is since elm/browser 1.0.2

Browser: Firefox 68.2.0esr
OS: Debian 10 "Buster"

**Comment by NoaVidovic** [comment]
Same issue here, in both Firefox 70.0.1 and Chrome 78 on Kubuntu 18.10

**Comment by tbash** [comment]
Fixed in master, thanks!
