### ISSUE TITLE
Ellie fails for projects containing Playground animations

### ISSUE THREAD

**Issue by pdamoc** [ellie-app/ellie#112]
It looks like Playground animations (`evancz/elm-playground`) trigger the `Map.!: ` bug. 
example:
https://ellie-app.com/7hr7gby7r9ma1

**Comment by pdamoc** [comment]
Upgrading the app to use `0.19.1` would probably get rid of this issue.

**Comment by tbash** [comment]
Your upgrade to `0.19.1` should fix this, thanks again!
