### ISSUE TITLE
Ellie "Elm not defined" error - generated code seems to be truncated

### ISSUE THREAD

**Issue by JamesHopkin** [ellie-app/ellie#115]
Experimenting with this program: https://ellie-app.com/7m3R2NFBcrja1
Now suddenly getting "Elm not defined" error. Javascript console is showing "Uncaught SyntaxError: Unexpected end of input". The following resource seems to be truncated:
https://ellie-app.com/r/workspace?token=SFMyNTY.g3QAAAACZAAEZGF0YW0AAAAkNzlhZGJiYzItNmNiNC00YjdiLWIzMGMtNjlmYjQ5ODRlZDM1ZAAGc2lnbmVkbgYAH6LZs24B.N-veadmtuF0VXbd6EeWx8YHA6RZK8sluloAf-YuDYPM&elmVersion=0.19.0

**Comment by tbash** [comment]
Upgrade to 0.19.1 should handle this, closing as that is in master. Thank you!
