### ISSUE TITLE
"Click to run" does not appear on Medium embeds

### ISSUE THREAD

**Issue by ckoster22** [ellie-app/ellie#56]
When I embed an ellie app on a Medium.com blog post the output tab shows "Ellie" but the "Click to run" instructions are not visible. Without those instructions it looks like output from the app is attempting to load but never succeeding.

![image](https://user-images.githubusercontent.com/8353821/42048644-73008d6c-7ac9-11e8-8095-23c0bdf068da.png)

As a side note, is clicking to run necessary? If someone clicks the output tab I think it's a fair assumption that the user expects to see it run automatically. Thoughts?

**Comment by lukewestby** [comment]
Fix is deploying right now. Click to run is necessary because you can append `?panel=output` to the embed url and have it show up automatically.
