### ISSUE TITLE
Add `How to run producation image` in Readme

### ISSUE THREAD

**Issue by Hajto** [ellie-app/ellie#62]
I've built image and run it, but I keep getting ws connection refused in logs.
```
WebSocket connection to 'ws://localhost:8000/api/sockets/websocket?vsn=2.0.0&token=SFMyNTY.g3QAAAACZAAEZGF0YW0AAAAkZjA2YTA4ZGItNTk0Zi00YzM5LTk5ZTYtZmRkYzMxZmJlYzQyZAAGc2lnbmVkbgYA0bwNGGYB.O_KskFpVWN6QAX6ufuARtR5eBZB8U-3zMHciVJhiUD4' failed: Error during WebSocket handshake: Unexpected response code: 403
```

It would be nice to get actual instructions how to launch production image and an example .env file with required env variables (I might be just blind and not see it though)

**Comment by tbash** [comment]
I agree with you, the way production images are being built/deployed is changing. Shortly after this task is complete, documentation will be available.

**Comment by Hajto** [comment]
@tbash I've set it for testing to ignore origin and it works like a charm.
