### ISSUE TITLE
Ellie won't start on IE11

### ISSUE THREAD

**Issue by popara** [ellie-app/ellie#65]
Tried to open it on ***IE11***
I got blank screen and following error message in the console.

SCRIPT438: Object doesn't support property or method 'assign'
editor-9a366741d8ec2ee332f9.js (1,59948)

(Fun fact, I wanted to test how Web Components play with IE11 ^^ )

**Comment by tbash** [comment]
Thanks for reporting! While I'm sure this could be solved with modifying the way the build is being transpiled, not supporting IE11 seems good for my health.
