### ISSUE TITLE
Cannot read property 'init' of undefined

### ISSUE THREAD

**Issue by evxn** [ellie-app/ellie#73]
https://ellie-app.com/48tX8QLg8Yya1

Looks like it doesn't support module names other than `Main`

**Comment by tbash** [comment]
Line 10 in your HTML should be ``

**Comment by tbash** [comment]
Line 10 in your HTML should be 
```js
   var app = Elm.Cube.init({ node: document.querySelector('main') })
```

https://ellie-app.com/4hbS8N9sfZba1
