### ISSUE TITLE
Dev environment setup

### ISSUE THREAD

**Issue by Maxim-Filimonov** [ellie-app/ellie#89]
Hi,
I have been trying to set up Ellie app locally to check if I can deploy it on K8 in SEA to help with regional issues(#87 )
So I started to setup docker as I don't have elixir installation on my local machine and found that the docker installation was part of Ellie at some point.
This commit https://github.com/ellie-app/ellie/commit/0d1e2a2e978964b6f568f403ffbdc430234fdbf0 removed all the docker related things.
I'm trying to understand what was the reason behind the decision to avoid digging myself into a rabbit hole.

**Comment by tbash** [comment]
Hello thanks for the offer to help! I have pinpointed the issue and am working a solution that will not require deployment to multiple regions. Docker was removed when I shifted to OTP releases using https://github.com/bitwalker/distillery along with the AWS CodePipeline and GitHub Webhooks. While it is possible to release Elixir apps in this way using Docker, I have more experience doing it without. As for the Docker dev environment, it feels faster to me to develop without (though I admit this may be all in my head and the ease of setup might out weigh this dev-latency, I've never benchmarked it).
