### ISSUE TITLE
Multiline strings are not correctly highlighted

### ISSUE THREAD

**Issue by Razzeee** [ellie-app/ellie#91]
```
test =
    """
    multiline string
    """
```
Ellie will highlight `"""` weird. Means first two will be green, last one will be red.

**Comment by tbash** [comment]
This seems to be a problem with CodeMirror's Elm syntax mode, it switches back to normal mode too early https://github.com/codemirror/CodeMirror/blob/master/mode/elm/elm.js#L143.

If I don't come up with a solution in the next day or so, I'll open up an issue with them.

**Comment by andys8** [comment]
It's even weirder if the first line has text (valid elm):
https://ellie-app.com/6S7T5dH4Vj5a1

![image](https://user-images.githubusercontent.com/13085980/66436364-252f6d00-ea27-11e9-9f4c-4987c0e18736.png)

**Comment by tbash** [comment]
Looks like Evan's version of this works from https://github.com/elm/elm-lang.org/blob/master/editor/cm/mode/elm.js, I copied what was there and opened a PR https://github.com/codemirror/CodeMirror/pull/6078. Pointing npm to my fork for now. Thank you both!
