### ISSUE TITLE
How to format the Elm code when working in ellie?

### ISSUE THREAD

**Issue by Viir** [ellie-app/ellie#92]
I have a question to ellie users:
How do you format your Elm code in ellie? Is there a function somewhere to have it formatted directly in ellie?
Or do you copy&paste to perform the formatting with another editor?

I did not find a tool to do the formatting directly in ellie. Also, I did not find information about this in the [readme](https://github.com/ellie-app/ellie/blob/673c338e7fb96771271258db68c8456daa439aa5/README.md) and the [issues list on github](https://github.com/ellie-app/ellie/issues?utf8=%E2%9C%93&q=format)

Thank you in advance for sharing your experience.

**Comment by tbash** [comment]
There is a button on the top right of the Elm editor's header. Maybe this could be made more obvious, perhaps having the text "FORMAT" would be better instead of or beside the icon?
<img width="720" alt="Screen Shot 2019-04-12 at 4 19 31 PM" src="https://user-images.githubusercontent.com/13289102/56064293-a7242f00-5d3f-11e9-9609-6df4041b11e9.png">

**Comment by Viir** [comment]
> There is a button on the top right of the Elm editor's header.

Nice. And on the tooltip I also found the keyboard command `SHIFT` + `F` to format. 👍

> Maybe this could be made more obvious, perhaps having the text "FORMAT" would be better instead of or beside the icon?

In my case, having the text `Format` there would have made it easier to find this button. Also, having the text in the button enables finding it with text search in chrome (Chrome text search does not seem to pick up the 'Format' text contained in the buttons `title` property)

I remember that I was using other buttons (for example the ones on the left, way larger) to see if I can find some kind of guide or a list of keyboard commands.
