### ISSUE TITLE
Can't use Ellie - Uncaught TypeError: Cannot read property 'replaceData' of undefined

### ISSUE THREAD

**Issue by TheunisKotze** [ellie-app/ellie#93]
Whenever I attempt to use Ellie by visiting https://ellie-app.com I am stuck on the loading screen and get a continuously logging error:
2189editor-301d310bee2d62b52911.js?vsn=d:1 Uncaught TypeError: Cannot read property 'replaceData' of undefined
    at te (editor-301d310bee2d62b52911.js?vsn=d:1)
    at ee (editor-301d310bee2d62b52911.js?vsn=d:1)
    at re (editor-301d310bee2d62b52911.js?vsn=d:1)
    at editor-301d310bee2d62b52911.js?vsn=d:1
    at t (editor-301d310bee2d62b52911.js?vsn=d:1)

I've tried to clear local storage / cookies etc. 
Running Chrome Version 73.0.3683.103 (Official Build) (64-bit)

**Comment by tbash** [comment]
This is known issue with some Chrome extensions and Elm apps in general, are you using any? If so, which one(s)?

**Comment by TheunisKotze** [comment]
Ah thanks for the quick response, I found the culprit (a website blocker)
