### ISSUE TITLE
How to import an Elm package before publishing to package.elm-lang.org?

### ISSUE THREAD

**Issue by Viir** [ellie-app/ellie#94]
How can I import a package in ellie before publishing it to package.elm-lang.org?
Do I need to publish a package before testing it in ellie?

**Comment by tbash** [comment]
There is not a way to do this, you would need to publish your package first. We rely on the standard Elm toolkit to fetch dependencies (from some `elm.json`) and compile, this makes use of https://package.elm-lang.org. There has been some thought around adding modules other the `Main` but I fear this will only add complexity to a service with simpler intent.

**Comment by Viir** [comment]
Thank you @tbash for the clarification!
