### ISSUE TITLE
Improve errror message when `main` is missing

### ISSUE THREAD

**Issue by andys8** [ellie-app/ellie#98]
I tried an example and didn't notice there wasn't a `main` function defined. The error is:

> Uncaught ReferenceError: Elm is not defined

![image](https://user-images.githubusercontent.com/13085980/60657590-e307f580-9e51-11e9-9d12-098fb929420e.png)

https://ellie-app.com/5ZbbK4t8krra1

I think we can improve the situation by adding a more descriptive error for this case. It is likely to happen if you're new to elm, too.

**Comment by tbash** [comment]
Fixed in master, I believe upgrading to 0.19.1 provided a sufficient solution.

<img width="903" alt="Screen Shot 2019-12-01 at 5 59 05 PM" src="https://user-images.githubusercontent.com/13289102/69921847-601cb280-1464-11ea-8116-fc19b590b5af.png">
